### ISSUE TITLE
 需求：对于Subtask的hack以及一种另类的赛制

### ISSUE THREAD

**Issue by cnyali-lk** [ExOJ/survey#16]
我有一个设想：
对于使用了Subtask的题，可以对某个选手的某个Subtask进行Hack。
如果Hack成功那么这组数据就加入这个Subtask。并且重测所有通过这个Subtask的人的这个数据点。
以此我想到了另外一种赛制，基于IOI和TC。
首先有一定的时间让选手做题（实时反馈有Subtask），接下来休息一小段时间，然后开始对着别人的代码Hack。
可以hack某个Subtask，如果成功则Hacker的总分+这个Subtask分数的1/10，否则-这个Subtask分数的1/20。
最后再Final Test。
当然结果也兹磁显示成功的次数及总加分，失败次数及总扣分

**Comment by billchenchina** [comment]
自定义规则 + plugin 化应该能够解决这个问题 goto #3
