### ISSUE TITLE
需求：复杂的评测类型及Hack

### ISSUE THREAD

**Issue by hewenyang** [ExOJ/survey#2]
除了传统题、交互题、通信题等以外实现任意复杂的题目类型，例如允许通过spj运行选手的多个程序的多个副本并分别指定时间和空间限制，允许多个程序直接通信等。
可能出现的应用场景：
1.密码学通信题：需要通过Hack引入中间人或者恶意的Alice或Bob并进行评测，需要允许中间人与双方通信；
2.并行计算题：在测评机配置足够的情况下通过多核CPU和大内存允许多线程计算等

**Comment by Ruanxingzhi** [comment]
goto #3 ;
