### ISSUE TITLE
需求：ioi赛制

### ISSUE THREAD

**Issue by Ruanxingzhi** [ExOJ/survey#4]
OI和ACM作为基本赛制，应当予以支持。
现在考虑的是ioi赛制。随着WC采用ioi，可以预见，ioi赛制将在中国一步一步普及，而现在的各种oj对于ioi赛制的支持是缺乏的。（uoj支持，然而uoj配置题目十分蛋疼）

ioi赛制是时代的选择。我们需要支持ioi赛制。

**Comment by CommonAnts** [comment]
建议实现更加可定制的赛制（类似Codeforces），参见 LibreOJ 比赛系统文档 2.2.4 节。

**Comment by billchenchina** [comment]
见 #3  建议 plugin 并随 OJ 赠送

**Comment by Ruanxingzhi** [comment]
goto #3 ;
